var frases = [
    "Você é a melodia mais linda que meu coração já ouviu.",
    "Seu sorriso ilumina meu dia mais do que o sol.",
    "Seus olhos são como estrelas brilhando em uma noite escura.",
    "Seu abraço é meu refúgio, meu lugar seguro no mundo.",
    "Sua beleza é de tirar o fôlego, mas sua alma é ainda mais encantadora.",
    "Você é a mulher dos meus sonhos, a personificação do amor.",
    "Ao seu lado, me sinto completo, como se todas as peças do quebra-cabeça se encaixassem.",
    "Seu amor me transforma, me faz querer ser uma pessoa melhor a cada dia.",
    "Sua inteligência e perspicácia me inspiram e me desafiam.",
    "Sua risada é contagiante, capaz de dissipar qualquer tristeza.",
    "Você é a minha melhor amiga, confidente e amante, tudo em uma só pessoa.",
    "Sua força e determinação são admiráveis, você é uma verdadeira guerreira.",
    "Sua bondade e compaixão tocam meu coração profundamente.",
    "Seu apoio incondicional me dá forças para enfrentar qualquer obstáculo.",
    "Sua presença em minha vida é um presente que valorizo mais do que qualquer coisa.",
    "Você é a luz que guia meus passos, a estrela que ilumina meu caminho.",
    "Seu amor é o combustível que me move, a força que me impulsiona.",
    "Cada momento ao seu lado é um tesouro que guardo em meu coração.",
    "Sua beleza interior brilha mais do que qualquer joia.",
    "Você é a definição de perfeição, a mulher que sempre sonhei em ter ao meu lado.",
    "Seu toque é mágico, capaz de acalmar minha alma e despertar meu corpo.",
    "Seu cheiro é inebriante, me envolve em um abraço de amor e paixão.",
    "Sua voz é como música para meus ouvidos, suave e melodiosa.",
    "Seus beijos são como gotas de chuva em um dia de verão, refrescantes e apaixonantes.",
    "Seu amor é a poesia mais linda que já li, a canção mais doce que já ouvi.",
    "Você é a obra de arte mais perfeita que já vi, uma verdadeira obra-prima.",
    "Seu sorriso é o arco-íris que colore meus dias cinzentos.",
    "Seus olhos são o oceano em que me perco, profundo e misterioso.",
    "Seu amor é o sol que aquece meu coração, a lua que ilumina minhas noites.",
    "Você é a flor mais rara e preciosa do meu jardim.",
    "Sua elegância e graça me encantam, você é uma verdadeira dama.",
    "Sua paixão pela vida é contagiante, me inspira a viver cada momento intensamente.",
    "Sua criatividade e imaginação me surpreendem a cada dia.",
    "Sua lealdade e honestidade são qualidades que admiro profundamente.",
    "Sua energia positiva ilumina qualquer ambiente, você é um raio de sol.",
    "Sua capacidade de perdoar e seguir em frente é inspiradora.",
    "Sua generosidade e altruísmo me comovem, você tem um coração de ouro.",
    "Sua coragem e ousadia me motivam a superar meus medos.",
    "Sua simpatia e carisma conquistam a todos ao seu redor.",
    "Sua autenticidade e transparência me fazem te amar ainda mais.",
    "Você é a minha musa, a inspiração para meus sonhos e realizações.",
    "Seu amor me faz sentir invencível, capaz de conquistar o mundo.",
    "Sua presença me completa, me faz sentir inteiro e feliz.",
    "Seu carinho e afeto são o bálsamo que cura minhas feridas.",
    "Sua compreensão e paciência me ajudam a crescer e evoluir.",
    "Sua capacidade de me fazer rir é um dos seus maiores encantos.",
    "Seu amor é o maior presente que a vida me deu.",
    "Você é a razão do meu sorriso, a melodia do meu coração.",
    "Seu amor é a chama que mantém acesa a paixão em nosso relacionamento.",
    "Você é a minha alma gêmea, a outra metade que me completa.",
    "Seu abraço é o meu porto seguro, onde encontro paz e conforto.",
    "Seu beijo é a faísca que acende o fogo da paixão em meu coração.",
    "Seu amor é a força que me impulsiona a ser a melhor versão de mim mesmo.",
    "Você é a rainha do meu coração, a dona do meu amor.",
    "Seu sorriso é o sol que ilumina meus dias mais escuros.",
    "Seus olhos são o espelho da sua alma, pura e bondosa.",
    "Seu amor é o tesouro mais precioso que possuo.",
    "Você é a melodia que embala meus sonhos, a poesia que inspira meus versos.",
    "Seu amor é a luz que guia meus passos, a estrela que ilumina meu caminho.",
    "Você é a razão da minha felicidade, o motivo do meu sorriso.",
    "Seu amor é o presente mais valioso que a vida me deu.",
    "Você é a mulher que sempre sonhei em ter ao meu lado.",
    "Seu amor me faz sentir completo, realizado e feliz.",
    "Seu abraço é o meu refúgio, onde encontro paz e segurança.",
    "Seu beijo é a faísca que acende a chama da paixão em meu coração.",
    "Seu amor é a força que me impulsiona a ser a melhor versão de mim mesmo.",
    "Você é a rainha do meu coração, a dona do meu amor.",
    "Seu sorriso é o sol que ilumina meus dias mais escuros.",
    "Seus olhos são o espelho da sua alma, pura e bondosa.",
    "Seu amor é o tesouro mais precioso que possuo.",
    "Você é a melodia que embala meus sonhos, a poesia que inspira meus versos.",
    "Seu amor é a luz que guia meus passos, a estrela que ilumina meu caminho.",
    "Você é a razão da minha felicidade, o motivo do meu sorriso.",
    "Seu amor é o presente mais valioso que a vida me deu.",
    "Você é a mulher que sempre sonhei em ter ao meu lado.",
    "Seu amor me faz sentir completo, realizado e feliz.",
    "Seu abraço é o meu refúgio, onde encontro paz e segurança.",
    "Seu beijo é a faísca que acende a chama da paixão em meu coração.",
    "Seu amor é a força que me impulsiona a ser a melhor versão de mim mesmo.",
    "Você é a rainha do meu coração, a dona do meu amor.",
    "Seu sorriso é o sol que ilumina meus dias mais escuros.",
    "Seus olhos são o espelho da sua alma, pura e bondosa.",
    "Seu amor é o tesouro mais precioso que possuo.",
    "Você é a melodia que embala meus sonhos, a poesia que inspira meus versos.",
    "Seu amor é a luz que guia meus passos, a estrela que ilumina meu caminho.",
    "Você é a razão da minha felicidade, o motivo do meu sorriso.",
    "Seu amor é o presente mais valioso que a vida me deu.",
    "Você é a mulher que sempre sonhei em ter ao meu lado.",
    "Seu amor me faz sentir completo, realizado e feliz.",
    "Seu abraço é o meu refúgio, onde encontro paz e segurança.",
    "Seu beijo é a faísca que acende a chama da paixão em meu coração.",
    "Seu amor é a força que me impulsiona a ser a melhor versão de mim mesmo.",
    "Você é a rainha do meu coração, a dona do meu amor.",
    "Seu sorriso é o sol que ilumina meus dias mais escuros.",
    "Seus olhos são o espelho da sua alma, pura e bondosa.",
    "Seu amor é o tesouro mais precioso que possuo.",
    "Você é a melodia que embala meus sonhos, a poesia que inspira meus versos.",
    "Seu amor é a luz que guia meus passos, a estrela que ilumina meu caminho.",
    "Você é a razão da minha felicidade, o motivo do meu sorriso.",
    "Seu amor é o presente mais valioso que a vida me deu." 
];